# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 67d27d3d9e9f4d0e61f5d5ef1661fb59ea3760e0f0fa69578887e960bc5a01a53288566550ca861f5b2f789d626adf055ea180c14e4acb6444af9fa4eb112da3

test:
  secret_key_base: 18d78cebab4b08c4fa28eae84a6a06d5bc722f39f8c5caec0a07852a960ecc5dea275c2ecc0815ca5cd7d04f5063a14e4d3489e8afdac1c0e38f239da41fb9ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
